/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonTitle: typeof import('./src/components/CommonTitle/index.vue')['default']
    HomeHomeContent: typeof import('./src/views/home/HomeContent.vue')['default']
    HomeHomeContentInversion: typeof import('./src/views/home/HomeContentInversion.vue')['default']
    HomeHomeTrust: typeof import('./src/views/home/HomeTrust.vue')['default']
    MediaScreen: typeof import('./src/components/MediaScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/Test/index.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter/index.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader/index.vue')['default']
    TheHeaderMobile: typeof import('./src/components/TheHeader/Mobile.vue')['default']
    TheHeaderPC: typeof import('./src/components/TheHeader/PC.vue')['default']
  }
}
